name: Build App

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    
    - name: Build app (unsigned)
      run: |
        xcodebuild -scheme Promptify \
                   -configuration Release \
                   -derivedDataPath build \
                   CODE_SIGN_IDENTITY="" \
                   CODE_SIGNING_REQUIRED=NO \
                   CODE_SIGNING_ALLOWED=NO \
                   build
                   
    - name: Archive build artifacts
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: Promptify-build-${{ github.sha }}
        path: build/Build/Products/Release/Promptify.app
        retention-days: 7